[project]
name = "pkglite"
version = "0.1.0"
description = "pkglite for Python"
authors = [
    { name = "Nan Xiao", email = "nan.xiao1@msd.com" }
]
dependencies = [
    "gitignore-parser>=0.1.11",
    "rich>=13.9.4",
    "typer>=0.12.5",
]
readme = "README.md"

classifiers = [
  "Development Status :: 3 - Alpha",

  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Healthcare Industry",
  "Intended Audience :: Information Technology",

  "Topic :: Software Development :: Build Tools",
  "Topic :: System :: Archiving :: Packaging",

  "License :: OSI Approved :: MIT License",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

requires-python = ">= 3.10"

[project.scripts]
pkglite = "pkglite.main:app"

[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pkglite"]

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.8.6",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
addopts = "-v --cov=pkglite --cov-report html"
